// Copyright (c) Microsoft Open Technologies, Inc. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

namespace Microsoft.AspNet.Razor.TagHelpers
{
    /// <summary>
    /// Defines how a tag helper will utilize its inner HTML.
    /// </summary>
    public enum ContentBehavior
    {
        /// <summary>
        /// Indicates that the tag helper will not modify its inner HTML in any way. This is
        /// the default <see cref="ContentBehavior"/> for tag helpers.
        /// </summary>
        /// <remarks>Children of the current tag helper will execute after the parent tag helper.</remarks>
        None,

        /// <summary>
        /// Indicates that the tag helper wants anything within its tag builders inner HTML to be
        /// appended to content that is generated by its children.
        /// </summary>
        /// <remarks>Children of the current tag helper will execute after the parent tag helper.</remarks>
        Append,

        /// <summary>
        /// Indicates that the tag helper will modify its HTML content. Therefore this <see cref="ContentBehavior"/>
        /// will enable tag helpers to examine a tag builders inner HTML.
        /// </summary>
        /// <remarks>Children of the current tag helper will execute before the parent tag helper.</remarks>
        Modify,

        /// <summary>
        /// Indicates that the tag helper wants anything within its tag builders inner HTML to be
        /// prepended to the body of the generated tag.
        /// </summary>
        /// <remarks>Children of the current tag helper will execute after the parent tag helper.</remarks>
        Prepend,

        /// <summary>
        /// Indicates that the tag helper wants anything within its tag builders inner HTML to
        /// replace any HTML inside of it.
        /// </summary>
        /// <remarks>Children of the current tag helper will not execute.</remarks>
        Replace,
    }
}